'use client';

import { useState, useEffect, useCallback } from 'react';
import {
  Bot,
  Brain,
  Zap,
  Check,
  X,
  AlertCircle,
  CheckCircle,
  Clock,
  TrendingUp,
  Activity,
  Sparkles,
  Target,
  Shield,
  Eye,
  RefreshCw,
  Download,
  Loader2,
  ChevronRight,
  Star,
  Dna,
  Users,
  Gauge,
  Wifi,
  WifiOff
} from 'lucide-react';
import clsx from 'clsx';

import { API_BASE } from '@/lib/api';

// Bot Card Component - Visual representation with symbol
function BotCard({ bot, onSelect, isSelected }: { bot: AutoGenBot; onSelect: () => void; isSelected: boolean }) {
  // Generate unique color gradient based on personality
  const gradients: Record<string, string> = {
    aggressive: 'from-red-500 to-orange-600',
    conservative: 'from-blue-500 to-cyan-600',
    balanced: 'from-green-500 to-emerald-600',
    opportunistic: 'from-yellow-500 to-amber-600',
    systematic: 'from-purple-500 to-violet-600',
    adaptive: 'from-pink-500 to-rose-600',
    contrarian: 'from-indigo-500 to-blue-600',
    momentum: 'from-orange-500 to-red-600',
    value: 'from-teal-500 to-green-600',
    hybrid: 'from-fuchsia-500 to-purple-600',
  };

  // Generate symbol based on abilities
  const getSymbol = () => {
    if (bot.abilities.includes('trading')) return <TrendingUp className="w-5 h-5" />;
    if (bot.abilities.includes('analysis')) return <Eye className="w-5 h-5" />;
    if (bot.abilities.includes('risk_management')) return <Shield className="w-5 h-5" />;
    return <Bot className="w-5 h-5" />;
  };

  const gradient = gradients[bot.personality] || 'from-slate-500 to-slate-600';
  const isActive = bot.state === 'working' || bot.state === 'trading';

  return (
    <div
      onClick={onSelect}
      className={clsx(
        'relative cursor-pointer rounded-xl p-4 transition-all duration-200 hover:scale-105',
        'bg-gradient-to-br border',
        isSelected ? 'ring-2 ring-time-primary border-time-primary' : 'border-slate-700/50 hover:border-slate-600'
      )}
    >
      {/* TIME Generated Badge */}
      <div className="absolute -top-2 -right-2 w-6 h-6 rounded-full bg-gradient-to-br from-emerald-400 to-green-500 flex items-center justify-center shadow-lg">
        <Sparkles className="w-3 h-3 text-white" />
      </div>

      {/* Active Indicator */}
      {isActive && (
        <div className="absolute top-3 left-3 w-2 h-2 rounded-full bg-green-400 animate-pulse" />
      )}

      {/* Bot Avatar */}
      <div className={`w-14 h-14 mx-auto rounded-xl bg-gradient-to-br ${gradient} flex items-center justify-center mb-3 shadow-lg`}>
        <div className="text-white">
          {getSymbol()}
        </div>
      </div>

      {/* Bot Name */}
      <h4 className="text-sm font-semibold text-white text-center truncate">{bot.name}</h4>

      {/* Quick Stats */}
      <div className="flex items-center justify-center gap-2 mt-2">
        <span className="text-xs text-green-400">{bot.performance.tradingWinRate}</span>
        <span className="text-xs text-slate-600">|</span>
        <span className="text-xs text-slate-400">G{bot.generation}</span>
      </div>

      {/* Personality Tag */}
      <div className="flex justify-center mt-2">
        <span className={`px-2 py-0.5 text-[10px] rounded-full bg-slate-800/80 text-slate-400 capitalize`}>
          {bot.personality}
        </span>
      </div>

      {/* Tap to view hint */}
      <p className="text-[10px] text-slate-600 text-center mt-2">Tap to view</p>
    </div>
  );
}

// Types
interface PendingBot {
  fileId: string;
  filename: string;
  rating: number;
  strategyType: string[];
  riskProfile: string;
  detectedAt: string;
  codeQuality: number;
  uniqueness: number;
}

interface Blueprint {
  id: string;
  name: string;
  description: string;
  confidence: number;
  predictedWinRate: number;
  predictedProfitFactor: number;
  abilities: string[];
  personality: string;
  strategies: string[];
  generatedAt: string;
}

interface AutoGenBot {
  id: string;
  name: string;
  description: string;
  abilities: string[];
  personality: string;
  generation: number;
  state: string;
  performance: {
    totalTasks: number;
    successRate: string;
    tradingWinRate: string;
    profitFactor: string;
  };
}

interface DashboardStats {
  observations: {
    total: number;
    trades: number;
    bots: number;
    regimes: number;
  };
  wisdom: {
    totalPatterns: number;
    tradePatterns: number;
    botPatterns: number;
    highConfidence: number;
  };
  blueprints: {
    total: number;
    best: { name: string; confidence: number } | null;
  };
  autoGeneratedBots: {
    total: number;
    active: number;
    topPerformer: string | null;
  };
}

export default function DropzonePage() {
  // State
  const [pendingBots, setPendingBots] = useState<PendingBot[]>([]);
  const [blueprints, setBlueprints] = useState<Blueprint[]>([]);
  const [autoGenBots, setAutoGenBots] = useState<AutoGenBot[]>([]);
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isConnected, setIsConnected] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [notification, setNotification] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const [activeTab, setActiveTab] = useState<'pending' | 'blueprints' | 'autogen' | 'wisdom'>('pending');
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [selectedBot, setSelectedBot] = useState<string | null>(null);

  // Fetch data
  const fetchData = useCallback(async () => {
    try {
      // Fetch pending bots
      const pendingRes = await fetch(`${API_BASE}/bot-brain/pending-absorption`);
      if (pendingRes.ok) {
        const pendingData = await pendingRes.json();
        if (pendingData.success) {
          setPendingBots(pendingData.pending || []);
        }
      }

      // Fetch blueprints
      const blueprintsRes = await fetch(`${API_BASE}/auto-perfect-bot/blueprints`);
      if (blueprintsRes.ok) {
        const blueprintsData = await blueprintsRes.json();
        if (blueprintsData.success) {
          setBlueprints(blueprintsData.blueprints || []);
        }
      }

      // Fetch auto-generated bots
      const autoGenRes = await fetch(`${API_BASE}/auto-perfect-bot/auto-generated-bots`);
      if (autoGenRes.ok) {
        const autoGenData = await autoGenRes.json();
        if (autoGenData.success) {
          setAutoGenBots(autoGenData.bots || []);
        }
      }

      // Fetch dashboard stats
      const dashboardRes = await fetch(`${API_BASE}/auto-perfect-bot/dashboard`);
      if (dashboardRes.ok) {
        const dashboardData = await dashboardRes.json();
        if (dashboardData.success) {
          setStats(dashboardData.dashboard);
        }
      }

      setIsConnected(true);
    } catch (error) {
      console.error('Failed to fetch data:', error);
      setIsConnected(false);
      // Generate sample data
      generateSampleData();
    } finally {
      setIsLoading(false);
      setIsRefreshing(false);
    }
  }, []);

  const generateSampleData = () => {
    setPendingBots([
      {
        fileId: 'bot-1',
        filename: 'Momentum_Scalper_Pro.mq5',
        rating: 4.6,
        strategyType: ['scalping', 'momentum'],
        riskProfile: 'moderate',
        detectedAt: new Date().toISOString(),
        codeQuality: 92,
        uniqueness: 78,
      },
      {
        fileId: 'bot-2',
        filename: 'AI_Trend_Follower.py',
        rating: 4.3,
        strategyType: ['trend_following', 'ml'],
        riskProfile: 'conservative',
        detectedAt: new Date(Date.now() - 3600000).toISOString(),
        codeQuality: 88,
        uniqueness: 85,
      },
    ]);

    setBlueprints([
      {
        id: 'bp-1',
        name: 'Alpha Master v2847',
        description: 'Auto-generated perfect bot based on 1,500 data points of analyzed wisdom',
        confidence: 0.89,
        predictedWinRate: 0.72,
        predictedProfitFactor: 2.1,
        abilities: ['trading', 'analysis', 'risk_management'],
        personality: 'balanced',
        strategies: ['trend_following', 'mean_reversion'],
        generatedAt: new Date().toISOString(),
      },
    ]);

    setStats({
      observations: { total: 2847, trades: 1256, bots: 892, regimes: 45 },
      wisdom: { totalPatterns: 567, tradePatterns: 234, botPatterns: 189, highConfidence: 89 },
      blueprints: { total: 12, best: { name: 'Alpha Master', confidence: 0.89 } },
      autoGeneratedBots: { total: 5, active: 3, topPerformer: 'AI Fusion Pro' },
    });
  };

  useEffect(() => {
    fetchData();
    const interval = setInterval(fetchData, 30000);
    return () => clearInterval(interval);
  }, [fetchData]);

  const handleRefresh = () => {
    setIsRefreshing(true);
    fetchData();
  };

  // Actions
  const handleApprove = async (fileId: string) => {
    setActionLoading(fileId);
    try {
      const res = await fetch(`${API_BASE}/bot-brain/approve/${fileId}`, { method: 'POST' });
      if (res.ok) {
        setPendingBots(prev => prev.filter(b => b.fileId !== fileId));
        setNotification({ type: 'success', message: 'Bot approved and absorbed!' });
      }
    } catch (error) {
      setNotification({ type: 'error', message: 'Failed to approve bot' });
    } finally {
      setActionLoading(null);
      setTimeout(() => setNotification(null), 3000);
    }
  };

  const handleReject = async (fileId: string) => {
    setActionLoading(fileId);
    try {
      const res = await fetch(`${API_BASE}/bot-brain/reject/${fileId}`, { method: 'POST' });
      if (res.ok) {
        setPendingBots(prev => prev.filter(b => b.fileId !== fileId));
        setNotification({ type: 'success', message: 'Bot rejected' });
      }
    } catch (error) {
      setNotification({ type: 'error', message: 'Failed to reject bot' });
    } finally {
      setActionLoading(null);
      setTimeout(() => setNotification(null), 3000);
    }
  };

  const handleCreateFromBlueprint = async (blueprintId: string) => {
    setActionLoading(blueprintId);
    try {
      const res = await fetch(`${API_BASE}/auto-perfect-bot/blueprints/${blueprintId}/create-bot`, { method: 'POST' });
      const data = await res.json();
      if (data.success) {
        setNotification({ type: 'success', message: `Perfect bot "${data.bot.name}" created!` });
        fetchData();
      }
    } catch (error) {
      setNotification({ type: 'error', message: 'Failed to create bot' });
    } finally {
      setActionLoading(null);
      setTimeout(() => setNotification(null), 3000);
    }
  };

  const handleForceGenerateBlueprint = async () => {
    setActionLoading('generate-blueprint');
    try {
      const res = await fetch(`${API_BASE}/auto-perfect-bot/force-generate-blueprint`, { method: 'POST' });
      const data = await res.json();
      if (data.success) {
        setNotification({ type: 'success', message: `Blueprint "${data.blueprint.name}" generated!` });
        fetchData();
      }
    } catch (error) {
      setNotification({ type: 'error', message: 'Failed to generate blueprint' });
    } finally {
      setActionLoading(null);
      setTimeout(() => setNotification(null), 3000);
    }
  };

  const handleForceGenerateBot = async () => {
    setActionLoading('generate-bot');
    try {
      const res = await fetch(`${API_BASE}/auto-perfect-bot/force-generate-bot`, { method: 'POST' });
      const data = await res.json();
      if (data.success) {
        setNotification({ type: 'success', message: `Perfect bot "${data.bot.name}" auto-generated!` });
        fetchData();
      }
    } catch (error) {
      setNotification({ type: 'error', message: 'Failed to generate bot' });
    } finally {
      setActionLoading(null);
      setTimeout(() => setNotification(null), 3000);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="text-center">
          <Loader2 className="w-12 h-12 text-time-primary mx-auto animate-spin mb-4" />
          <p className="text-white font-medium">Loading Bot Brain...</p>
          <p className="text-sm text-slate-400 mt-1">Connecting to intelligence systems</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Notification */}
      {notification && (
        <div className={`fixed top-4 right-4 z-50 flex items-center gap-2 px-4 py-3 rounded-lg shadow-lg ${
          notification.type === 'success' ? 'bg-green-500/20 border border-green-500/50 text-green-400' : 'bg-red-500/20 border border-red-500/50 text-red-400'
        }`}>
          {notification.type === 'success' ? <CheckCircle className="w-5 h-5" /> : <AlertCircle className="w-5 h-5" />}
          <span className="text-sm font-medium">{notification.message}</span>
          <button onClick={() => setNotification(null)} className="ml-2 hover:opacity-80">
            <X className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <Brain className="w-8 h-8 text-purple-400" />
            Bot Brain & Dropzone
          </h1>
          <p className="text-slate-400">Auto-watches, learns, and generates perfect bots</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-slate-800/50">
            {isConnected ? (
              <Wifi className="w-4 h-4 text-green-400" />
            ) : (
              <WifiOff className="w-4 h-4 text-yellow-400" />
            )}
            <span className="text-xs text-slate-400">{isConnected ? 'Live' : 'Local'}</span>
          </div>
          <button
            onClick={handleRefresh}
            disabled={isRefreshing}
            className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`w-4 h-4 text-slate-400 ${isRefreshing ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      {stats && (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="card p-4">
            <div className="flex items-center gap-3 mb-2">
              <Eye className="w-5 h-5 text-blue-400" />
              <span className="text-sm text-slate-400">Observations</span>
            </div>
            <p className="text-2xl font-bold text-white">{stats.observations.total.toLocaleString()}</p>
            <p className="text-xs text-slate-500">{stats.observations.trades} trades watched</p>
          </div>
          <div className="card p-4">
            <div className="flex items-center gap-3 mb-2">
              <Sparkles className="w-5 h-5 text-yellow-400" />
              <span className="text-sm text-slate-400">Wisdom Patterns</span>
            </div>
            <p className="text-2xl font-bold text-white">{stats.wisdom.totalPatterns}</p>
            <p className="text-xs text-slate-500">{stats.wisdom.highConfidence} high confidence</p>
          </div>
          <div className="card p-4">
            <div className="flex items-center gap-3 mb-2">
              <Target className="w-5 h-5 text-purple-400" />
              <span className="text-sm text-slate-400">Blueprints</span>
            </div>
            <p className="text-2xl font-bold text-white">{stats.blueprints.total}</p>
            <p className="text-xs text-slate-500">{stats.blueprints.best ? `Best: ${stats.blueprints.best.name}` : 'None yet'}</p>
          </div>
          <div className="card p-4">
            <div className="flex items-center gap-3 mb-2">
              <Bot className="w-5 h-5 text-green-400" />
              <span className="text-sm text-slate-400">Auto-Generated</span>
            </div>
            <p className="text-2xl font-bold text-white">{stats.autoGeneratedBots.total}</p>
            <p className="text-xs text-slate-500">{stats.autoGeneratedBots.active} active</p>
          </div>
        </div>
      )}

      {/* Quick Actions */}
      <div className="card p-4">
        <h3 className="text-sm font-semibold text-slate-400 mb-3">QUICK ACTIONS</h3>
        <div className="flex flex-wrap gap-3">
          <button
            onClick={handleForceGenerateBlueprint}
            disabled={actionLoading === 'generate-blueprint'}
            className="flex items-center gap-2 px-4 py-2 bg-purple-500/20 hover:bg-purple-500/30 border border-purple-500/50 rounded-lg text-purple-400 transition-colors disabled:opacity-50"
          >
            {actionLoading === 'generate-blueprint' ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4" />
            )}
            Generate Blueprint Now
          </button>
          <button
            onClick={handleForceGenerateBot}
            disabled={actionLoading === 'generate-bot'}
            className="flex items-center gap-2 px-4 py-2 bg-green-500/20 hover:bg-green-500/30 border border-green-500/50 rounded-lg text-green-400 transition-colors disabled:opacity-50"
          >
            {actionLoading === 'generate-bot' ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Bot className="w-4 h-4" />
            )}
            Generate Perfect Bot Now
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 border-b border-slate-700/50">
        {[
          { id: 'pending', label: 'Pending Approval', icon: Clock, count: pendingBots.length },
          { id: 'blueprints', label: 'Blueprints', icon: Target, count: blueprints.length },
          { id: 'autogen', label: 'Auto-Generated', icon: Bot, count: autoGenBots.length },
          { id: 'wisdom', label: 'Wisdom', icon: Sparkles },
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as typeof activeTab)}
            className={clsx(
              'flex items-center gap-2 px-4 py-3 border-b-2 transition-colors',
              activeTab === tab.id
                ? 'border-time-primary text-time-primary'
                : 'border-transparent text-slate-400 hover:text-white'
            )}
          >
            <tab.icon className="w-4 h-4" />
            {tab.label}
            {tab.count !== undefined && tab.count > 0 && (
              <span className="px-2 py-0.5 text-xs bg-slate-700 rounded-full">{tab.count}</span>
            )}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="min-h-[400px]">
        {/* Pending Approval Tab */}
        {activeTab === 'pending' && (
          <div className="space-y-4">
            {pendingBots.length === 0 ? (
              <div className="card p-12 text-center">
                <CheckCircle className="w-12 h-12 mx-auto mb-4 text-green-400" />
                <h3 className="text-lg font-semibold text-white mb-2">All Clear!</h3>
                <p className="text-slate-400">No bots pending approval. Drop files in the dropzone folder to import.</p>
              </div>
            ) : (
              pendingBots.map(bot => (
                <div key={bot.fileId} className="card p-4">
                  <div className="flex items-start justify-between">
                    <div className="flex items-start gap-4">
                      <div className="p-3 rounded-lg bg-yellow-500/20">
                        <Clock className="w-6 h-6 text-yellow-400" />
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-white">{bot.filename}</h3>
                        <div className="flex items-center gap-4 mt-1 text-sm text-slate-400">
                          <span className="flex items-center gap-1">
                            <Star className="w-4 h-4 text-yellow-400" />
                            {bot.rating.toFixed(1)}/5.0
                          </span>
                          <span className="flex items-center gap-1">
                            <Shield className="w-4 h-4" />
                            {bot.riskProfile}
                          </span>
                          <span>Code Quality: {bot.codeQuality}%</span>
                          <span>Uniqueness: {bot.uniqueness}%</span>
                        </div>
                        <div className="flex gap-2 mt-2">
                          {bot.strategyType.map(type => (
                            <span key={type} className="px-2 py-0.5 text-xs bg-slate-700 rounded-full text-slate-300">
                              {type}
                            </span>
                          ))}
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => handleReject(bot.fileId)}
                        disabled={actionLoading === bot.fileId}
                        className="flex items-center gap-2 px-4 py-2 bg-red-500/20 hover:bg-red-500/30 border border-red-500/50 rounded-lg text-red-400 transition-colors disabled:opacity-50"
                      >
                        {actionLoading === bot.fileId ? <Loader2 className="w-4 h-4 animate-spin" /> : <X className="w-4 h-4" />}
                        Reject
                      </button>
                      <button
                        onClick={() => handleApprove(bot.fileId)}
                        disabled={actionLoading === bot.fileId}
                        className="flex items-center gap-2 px-4 py-2 bg-green-500/20 hover:bg-green-500/30 border border-green-500/50 rounded-lg text-green-400 transition-colors disabled:opacity-50"
                      >
                        {actionLoading === bot.fileId ? <Loader2 className="w-4 h-4 animate-spin" /> : <Check className="w-4 h-4" />}
                        Approve & Absorb
                      </button>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        )}

        {/* Blueprints Tab */}
        {activeTab === 'blueprints' && (
          <div className="space-y-4">
            {blueprints.length === 0 ? (
              <div className="card p-12 text-center">
                <Target className="w-12 h-12 mx-auto mb-4 text-slate-600" />
                <h3 className="text-lg font-semibold text-white mb-2">No Blueprints Yet</h3>
                <p className="text-slate-400 mb-4">Generate blueprints from accumulated wisdom</p>
                <button
                  onClick={handleForceGenerateBlueprint}
                  disabled={actionLoading === 'generate-blueprint'}
                  className="btn-primary"
                >
                  <Sparkles className="w-4 h-4 mr-2" />
                  Generate Blueprint
                </button>
              </div>
            ) : (
              blueprints.map(bp => (
                <div key={bp.id} className="card p-4">
                  <div className="flex items-start justify-between">
                    <div className="flex items-start gap-4">
                      <div className="p-3 rounded-lg bg-purple-500/20">
                        <Target className="w-6 h-6 text-purple-400" />
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-white">{bp.name}</h3>
                        <p className="text-sm text-slate-400 mt-1">{bp.description}</p>
                        <div className="flex items-center gap-4 mt-2 text-sm">
                          <span className="text-green-400">Win Rate: {(bp.predictedWinRate * 100).toFixed(1)}%</span>
                          <span className="text-blue-400">PF: {bp.predictedProfitFactor.toFixed(2)}</span>
                          <span className="text-purple-400">Confidence: {(bp.confidence * 100).toFixed(1)}%</span>
                        </div>
                        <div className="flex gap-2 mt-2">
                          {bp.abilities.slice(0, 4).map(ability => (
                            <span key={ability} className="px-2 py-0.5 text-xs bg-slate-700 rounded-full text-slate-300">
                              {ability}
                            </span>
                          ))}
                        </div>
                      </div>
                    </div>
                    <button
                      onClick={() => handleCreateFromBlueprint(bp.id)}
                      disabled={actionLoading === bp.id}
                      className="flex items-center gap-2 px-4 py-2 bg-time-primary/20 hover:bg-time-primary/30 border border-time-primary/50 rounded-lg text-time-primary transition-colors disabled:opacity-50"
                    >
                      {actionLoading === bp.id ? <Loader2 className="w-4 h-4 animate-spin" /> : <Bot className="w-4 h-4" />}
                      Create Perfect Bot
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        )}

        {/* Auto-Generated Tab */}
        {activeTab === 'autogen' && (
          <div className="space-y-4">
            {autoGenBots.length === 0 ? (
              <div className="card p-12 text-center">
                <Bot className="w-12 h-12 mx-auto mb-4 text-slate-600" />
                <h3 className="text-lg font-semibold text-white mb-2">No Auto-Generated Bots Yet</h3>
                <p className="text-slate-400 mb-4">The system will auto-generate perfect bots as it learns</p>
                <button
                  onClick={handleForceGenerateBot}
                  disabled={actionLoading === 'generate-bot'}
                  className="btn-primary"
                >
                  <Bot className="w-4 h-4 mr-2" />
                  Generate Perfect Bot Now
                </button>
              </div>
            ) : (
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                {autoGenBots.map(bot => (
                  <BotCard
                    key={bot.id}
                    bot={bot}
                    onSelect={() => setSelectedBot(selectedBot === bot.id ? null : bot.id)}
                    isSelected={selectedBot === bot.id}
                  />
                ))}
              </div>
            )}

            {/* Selected Bot Details Modal */}
            {selectedBot && (
              <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50" onClick={() => setSelectedBot(null)}>
                <div className="bg-slate-900 border border-slate-700 rounded-xl p-6 max-w-lg w-full mx-4" onClick={e => e.stopPropagation()}>
                  {(() => {
                    const bot = autoGenBots.find(b => b.id === selectedBot);
                    if (!bot) return null;
                    return (
                      <>
                        <div className="flex items-center justify-between mb-4">
                          <div className="flex items-center gap-3">
                            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-green-500 to-emerald-600 flex items-center justify-center">
                              <Sparkles className="w-6 h-6 text-white" />
                            </div>
                            <div>
                              <h3 className="text-lg font-bold text-white">{bot.name}</h3>
                              <span className="text-xs text-emerald-400">TIME Generated</span>
                            </div>
                          </div>
                          <button onClick={() => setSelectedBot(null)} className="text-slate-400 hover:text-white">
                            <X className="w-5 h-5" />
                          </button>
                        </div>
                        <p className="text-slate-400 text-sm mb-4">{bot.description}</p>
                        <div className="grid grid-cols-2 gap-4 mb-4">
                          <div className="bg-slate-800/50 rounded-lg p-3">
                            <p className="text-xs text-slate-500 mb-1">Win Rate</p>
                            <p className="text-xl font-bold text-green-400">{bot.performance.tradingWinRate}</p>
                          </div>
                          <div className="bg-slate-800/50 rounded-lg p-3">
                            <p className="text-xs text-slate-500 mb-1">Profit Factor</p>
                            <p className="text-xl font-bold text-blue-400">{bot.performance.profitFactor}</p>
                          </div>
                          <div className="bg-slate-800/50 rounded-lg p-3">
                            <p className="text-xs text-slate-500 mb-1">Success Rate</p>
                            <p className="text-xl font-bold text-purple-400">{bot.performance.successRate}</p>
                          </div>
                          <div className="bg-slate-800/50 rounded-lg p-3">
                            <p className="text-xs text-slate-500 mb-1">Generation</p>
                            <p className="text-xl font-bold text-slate-300">Gen {bot.generation}</p>
                          </div>
                        </div>
                        <div className="flex flex-wrap gap-2 mb-4">
                          {bot.abilities.map(ability => (
                            <span key={ability} className="px-3 py-1 text-sm bg-time-primary/20 text-time-primary rounded-full">
                              {ability}
                            </span>
                          ))}
                        </div>
                        <div className="flex items-center justify-between text-sm">
                          <span className={clsx(
                            'flex items-center gap-2 px-3 py-1 rounded-full',
                            bot.state === 'working' || bot.state === 'trading' ? 'bg-green-500/20 text-green-400' :
                            bot.state === 'idle' ? 'bg-blue-500/20 text-blue-400' :
                            'bg-slate-500/20 text-slate-400'
                          )}>
                            <Activity className="w-4 h-4" />
                            {bot.state.charAt(0).toUpperCase() + bot.state.slice(1)}
                          </span>
                          <span className="text-slate-500">{bot.personality}</span>
                        </div>
                      </>
                    );
                  })()}
                </div>
              </div>
            )}
          </div>
        )}

        {/* Wisdom Tab */}
        {activeTab === 'wisdom' && stats && (
          <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="card p-4">
                <div className="flex items-center gap-3 mb-3">
                  <TrendingUp className="w-5 h-5 text-green-400" />
                  <h4 className="font-semibold text-white">Trade Patterns</h4>
                </div>
                <p className="text-3xl font-bold text-white mb-1">{stats.wisdom.tradePatterns}</p>
                <p className="text-sm text-slate-400">Patterns learned from trades</p>
                <div className="mt-3 h-2 bg-slate-700 rounded-full overflow-hidden">
                  <div className="h-full bg-green-400" style={{ width: `${Math.min(100, stats.wisdom.tradePatterns / 5)}%` }} />
                </div>
              </div>

              <div className="card p-4">
                <div className="flex items-center gap-3 mb-3">
                  <Bot className="w-5 h-5 text-blue-400" />
                  <h4 className="font-semibold text-white">Bot Patterns</h4>
                </div>
                <p className="text-3xl font-bold text-white mb-1">{stats.wisdom.botPatterns}</p>
                <p className="text-sm text-slate-400">Patterns learned from bots</p>
                <div className="mt-3 h-2 bg-slate-700 rounded-full overflow-hidden">
                  <div className="h-full bg-blue-400" style={{ width: `${Math.min(100, stats.wisdom.botPatterns / 5)}%` }} />
                </div>
              </div>

              <div className="card p-4">
                <div className="flex items-center gap-3 mb-3">
                  <Gauge className="w-5 h-5 text-purple-400" />
                  <h4 className="font-semibold text-white">High Confidence</h4>
                </div>
                <p className="text-3xl font-bold text-white mb-1">{stats.wisdom.highConfidence}</p>
                <p className="text-sm text-slate-400">Patterns with &gt;80% confidence</p>
                <div className="mt-3 h-2 bg-slate-700 rounded-full overflow-hidden">
                  <div className="h-full bg-purple-400" style={{ width: `${Math.min(100, stats.wisdom.highConfidence)}%` }} />
                </div>
              </div>
            </div>

            <div className="card p-6">
              <h4 className="font-semibold text-white mb-4 flex items-center gap-2">
                <Activity className="w-5 h-5 text-time-primary" />
                How It Works
              </h4>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                {[
                  { icon: Eye, title: 'Watch', desc: 'Observes every trade, bot action, and market regime change' },
                  { icon: Sparkles, title: 'Learn', desc: 'Extracts patterns from successes and failures' },
                  { icon: Target, title: 'Blueprint', desc: 'Creates blueprints for perfect bots based on wisdom' },
                  { icon: Bot, title: 'Generate', desc: 'Auto-generates perfect bots from blueprints' },
                ].map((step, i) => (
                  <div key={step.title} className="relative">
                    <div className="text-center">
                      <div className="w-12 h-12 rounded-full bg-time-primary/20 flex items-center justify-center mx-auto mb-3">
                        <step.icon className="w-6 h-6 text-time-primary" />
                      </div>
                      <h5 className="font-semibold text-white">{step.title}</h5>
                      <p className="text-xs text-slate-400 mt-1">{step.desc}</p>
                    </div>
                    {i < 3 && (
                      <ChevronRight className="hidden md:block absolute top-6 -right-2 w-5 h-5 text-slate-600" />
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
