/**
 * AUTO PERFECT BOT GENERATOR API ROUTES
 *
 * Frontend buttons for:
 * - Viewing wisdom (what the system has learned)
 * - Viewing blueprints (perfect bot designs)
 * - Force generating blueprints
 * - Force generating perfect bots
 * - Viewing observations
 * - Getting statistics
 */

import { Router, Request, Response } from 'express';
import { authMiddleware, adminMiddleware } from './auth';
import { autoPerfectBotGenerator } from '../bots/auto_perfect_bot_generator';
import { botBrain } from '../bots/bot_brain';

const router = Router();

// ============================================================
// PUBLIC ROUTES (For Dashboard Display)
// ============================================================

/**
 * GET /auto-perfect-bot/status
 * Get the status of the auto perfect bot generator
 */
router.get('/status', (req: Request, res: Response) => {
  const stats = autoPerfectBotGenerator.getStats();

  res.json({
    success: true,
    status: 'ONLINE',
    message: 'Auto Perfect Bot Generator is watching and learning',
    stats: {
      totalObservations: stats.totalObservations,
      tradesWatched: stats.tradesWatched,
      botsWatched: stats.botsWatched,
      regimesWatched: stats.regimesWatched,
      wisdomGenerated: stats.wisdomGenerated,
      blueprintsCreated: stats.blueprintsCreated,
      botsAutoGenerated: stats.botsAutoGenerated,
      perfectBotsActive: stats.perfectBotsActive,
      systemHealth: stats.systemHealth,
    },
    timestamps: {
      lastObservation: stats.lastObservation,
      lastWisdomUpdate: stats.lastWisdomUpdate,
      lastBotGenerated: stats.lastBotGenerated,
    },
  });
});

// ============================================================
// AUTHENTICATED ROUTES
// ============================================================

/**
 * GET /auto-perfect-bot/wisdom
 * Get all accumulated wisdom
 */
router.get('/wisdom', authMiddleware, (req: Request, res: Response) => {
  const wisdom = autoPerfectBotGenerator.getWisdom();

  res.json({
    success: true,
    wisdom: {
      trade: {
        count: wisdom.trade.length,
        items: wisdom.trade.slice(0, 50), // Limit for response size
        summary: {
          avgWinRate: wisdom.trade.length > 0
            ? wisdom.trade.reduce((sum, w) => sum + w.winRate, 0) / wisdom.trade.length
            : 0,
          highConfidencePatterns: wisdom.trade.filter(w => w.confidence > 0.8).length,
        },
      },
      bot: {
        count: wisdom.bot.length,
        items: wisdom.bot.slice(0, 50),
        summary: {
          botsAnalyzed: wisdom.bot.length,
          avgConfidence: wisdom.bot.length > 0
            ? wisdom.bot.reduce((sum, w) => sum + w.confidence, 0) / wisdom.bot.length
            : 0,
        },
      },
      regime: {
        count: wisdom.regime.length,
        items: wisdom.regime,
        summary: {
          regimesLearned: wisdom.regime.length,
        },
      },
    },
  });
});

/**
 * GET /auto-perfect-bot/blueprints
 * Get all generated blueprints
 */
router.get('/blueprints', authMiddleware, (req: Request, res: Response) => {
  const blueprints = autoPerfectBotGenerator.getBlueprints();

  res.json({
    success: true,
    total: blueprints.length,
    blueprints: blueprints.map(bp => ({
      id: bp.id,
      name: bp.name,
      description: bp.description,
      confidence: bp.overallConfidence,
      predictedWinRate: bp.predictedWinRate,
      predictedProfitFactor: bp.predictedProfitFactor,
      predictedSharpe: bp.predictedSharpe,
      abilities: bp.optimalAbilities,
      personality: bp.optimalPersonality,
      strategies: bp.optimalStrategies,
      generatedAt: bp.generatedAt,
      totalDataPoints: bp.totalDataPoints,
      // BUTTON: Create Bot from this Blueprint
      actions: {
        createBot: {
          method: 'POST',
          url: `/api/auto-perfect-bot/blueprints/${bp.id}/create-bot`,
          label: '🤖 Create Perfect Bot',
        },
      },
    })),
  });
});

/**
 * GET /auto-perfect-bot/blueprints/best
 * Get the best blueprint
 */
router.get('/blueprints/best', authMiddleware, (req: Request, res: Response) => {
  const blueprint = autoPerfectBotGenerator.getBestBlueprint();

  if (!blueprint) {
    return res.json({
      success: false,
      message: 'No blueprints generated yet. Keep watching trades!',
      actions: {
        forceGenerate: {
          method: 'POST',
          url: '/api/auto-perfect-bot/force-generate-blueprint',
          label: '⚡ Force Generate Blueprint',
        },
      },
    });
  }

  res.json({
    success: true,
    blueprint: {
      ...blueprint,
      actions: {
        createBot: {
          method: 'POST',
          url: `/api/auto-perfect-bot/blueprints/${blueprint.id}/create-bot`,
          label: '🤖 Create This Perfect Bot',
        },
      },
    },
  });
});

/**
 * GET /auto-perfect-bot/observations
 * Get recent observations
 */
router.get('/observations', authMiddleware, (req: Request, res: Response) => {
  const limit = parseInt(req.query.limit as string) || 100;
  const observations = autoPerfectBotGenerator.getRecentObservations(limit);

  res.json({
    success: true,
    total: observations.length,
    observations: observations.map(obs => ({
      id: obs.id,
      type: obs.type,
      source: obs.source,
      impact: obs.impact,
      timestamp: obs.timestamp,
      processed: obs.processed,
      dataSummary: typeof obs.data === 'object' ? Object.keys(obs.data) : [],
    })),
  });
});

/**
 * GET /auto-perfect-bot/auto-generated-bots
 * Get all auto-generated perfect bots
 */
router.get('/auto-generated-bots', authMiddleware, (req: Request, res: Response) => {
  const allBots = botBrain.getAllBots();
  const autoGenBots = allBots.filter(b => b.mutations.includes('auto_generated'));

  res.json({
    success: true,
    total: autoGenBots.length,
    bots: autoGenBots.map(bot => ({
      id: bot.id,
      name: bot.name,
      description: bot.description,
      abilities: bot.abilities,
      personality: bot.personality,
      generation: bot.generation,
      state: bot.state,
      performance: {
        totalTasks: bot.performance.totalTasks,
        successRate: bot.performance.totalTasks > 0
          ? (bot.performance.successfulTasks / bot.performance.totalTasks * 100).toFixed(1) + '%'
          : 'N/A',
        tradingWinRate: (bot.performance.tradingWinRate * 100).toFixed(1) + '%',
        profitFactor: bot.performance.profitFactor.toFixed(2),
        totalPnL: bot.performance.totalPnL,
      },
      ratings: bot.ratings,
      createdAt: bot.createdAt,
      lastActiveAt: bot.lastActiveAt,
    })),
  });
});

// ============================================================
// ACTION ROUTES (Require Auth)
// ============================================================

/**
 * POST /auto-perfect-bot/force-generate-blueprint
 * BUTTON: Force generate a new blueprint from current wisdom
 */
router.post('/force-generate-blueprint', authMiddleware, (req: Request, res: Response) => {
  const blueprint = autoPerfectBotGenerator.forceGenerateBlueprint();

  if (!blueprint) {
    return res.status(400).json({
      success: false,
      error: 'Could not generate blueprint. Need more observations first.',
      suggestion: 'Record more trades and bot actions to build wisdom.',
    });
  }

  res.json({
    success: true,
    message: `🔮 Blueprint "${blueprint.name}" generated!`,
    blueprint: {
      id: blueprint.id,
      name: blueprint.name,
      description: blueprint.description,
      confidence: blueprint.overallConfidence,
      predictedWinRate: blueprint.predictedWinRate,
      predictedProfitFactor: blueprint.predictedProfitFactor,
      abilities: blueprint.optimalAbilities,
      strategies: blueprint.optimalStrategies,
    },
    actions: {
      createBot: {
        method: 'POST',
        url: `/api/auto-perfect-bot/blueprints/${blueprint.id}/create-bot`,
        label: '🤖 Create This Perfect Bot Now',
      },
    },
  });
});

/**
 * POST /auto-perfect-bot/force-generate-bot
 * BUTTON: Force generate a perfect bot immediately
 */
router.post('/force-generate-bot', authMiddleware, (req: Request, res: Response) => {
  const bot = autoPerfectBotGenerator.forceGeneratePerfectBot();

  if (!bot) {
    return res.status(400).json({
      success: false,
      error: 'Could not generate perfect bot. Need more wisdom first.',
      suggestion: 'Force generate a blueprint first, or record more observations.',
      actions: {
        generateBlueprint: {
          method: 'POST',
          url: '/api/auto-perfect-bot/force-generate-blueprint',
          label: '🔮 Generate Blueprint First',
        },
      },
    });
  }

  res.json({
    success: true,
    message: `🤖 PERFECT BOT "${bot.name}" AUTO-GENERATED!`,
    bot: {
      id: bot.id,
      name: bot.name,
      description: bot.description,
      abilities: bot.abilities,
      personality: bot.personality,
      specializations: bot.specializations,
      dna: bot.dna,
      generation: bot.generation,
    },
    actions: {
      viewBot: {
        method: 'GET',
        url: `/api/bot-brain/bots/${bot.id}`,
        label: '👁️ View Bot Details',
      },
      assignTask: {
        method: 'POST',
        url: `/api/bot-brain/assign-task`,
        label: '📋 Assign Task to Bot',
      },
    },
  });
});

/**
 * POST /auto-perfect-bot/blueprints/:blueprintId/create-bot
 * BUTTON: Create a bot from a specific blueprint
 */
router.post('/blueprints/:blueprintId/create-bot', authMiddleware, (req: Request, res: Response) => {
  const { blueprintId } = req.params;
  const blueprints = autoPerfectBotGenerator.getBlueprints();
  const blueprint = blueprints.find(b => b.id === blueprintId);

  if (!blueprint) {
    return res.status(404).json({
      success: false,
      error: 'Blueprint not found',
    });
  }

  // Create bot from blueprint
  const template = {
    name: blueprint.name,
    description: blueprint.description,
    basedOn: blueprint.wisdomSources,
    abilities: blueprint.optimalAbilities,
    personality: blueprint.optimalPersonality,
    strategies: blueprint.optimalStrategies,
    estimatedPerformance: {
      winRate: blueprint.predictedWinRate,
      profitFactor: blueprint.predictedProfitFactor,
      riskLevel: blueprint.optimalRiskProfile,
    },
    confidence: blueprint.overallConfidence,
  };

  const bot = botBrain.createBotFromTemplate(template);

  res.json({
    success: true,
    message: `🤖 Perfect Bot "${bot.name}" created from blueprint!`,
    bot: {
      id: bot.id,
      name: bot.name,
      description: bot.description,
      abilities: bot.abilities,
      personality: bot.personality,
    },
    predictedPerformance: {
      winRate: (blueprint.predictedWinRate * 100).toFixed(1) + '%',
      profitFactor: blueprint.predictedProfitFactor.toFixed(2),
      sharpe: blueprint.predictedSharpe.toFixed(2),
      maxDrawdown: blueprint.predictedDrawdown.toFixed(1) + '%',
    },
  });
});

/**
 * POST /auto-perfect-bot/record-trade
 * Record a trade for learning
 */
router.post('/record-trade', authMiddleware, (req: Request, res: Response) => {
  const trade = req.body;

  if (!trade.botId || !trade.symbol || !trade.direction || trade.pnl === undefined) {
    return res.status(400).json({
      success: false,
      error: 'Missing required trade fields: botId, symbol, direction, pnl',
    });
  }

  autoPerfectBotGenerator.recordTrade({
    botId: trade.botId,
    symbol: trade.symbol,
    direction: trade.direction,
    entryPrice: trade.entryPrice || 0,
    exitPrice: trade.exitPrice || 0,
    pnl: trade.pnl,
    indicators: trade.indicators || [],
    timeframe: trade.timeframe || 'H1',
    regime: trade.regime || 'unknown',
  });

  res.json({
    success: true,
    message: 'Trade recorded and added to learning queue',
  });
});

/**
 * POST /auto-perfect-bot/record-regime-change
 * Record a regime change for learning
 */
router.post('/record-regime-change', authMiddleware, (req: Request, res: Response) => {
  const { from, to, duration, triggerEvents } = req.body;

  if (!from || !to) {
    return res.status(400).json({
      success: false,
      error: 'Missing required fields: from, to',
    });
  }

  autoPerfectBotGenerator.recordRegimeChange({
    from,
    to,
    duration: duration || 0,
    triggerEvents: triggerEvents || [],
  });

  res.json({
    success: true,
    message: 'Regime change recorded and added to learning queue',
  });
});

// ============================================================
// ADMIN ROUTES
// ============================================================

/**
 * GET /auto-perfect-bot/admin/full-stats
 * Get complete statistics (admin only)
 */
router.get('/admin/full-stats', authMiddleware, adminMiddleware, (req: Request, res: Response) => {
  const stats = autoPerfectBotGenerator.getStats();
  const wisdom = autoPerfectBotGenerator.getWisdom();
  const blueprints = autoPerfectBotGenerator.getBlueprints();
  const observations = autoPerfectBotGenerator.getRecentObservations(1000);

  res.json({
    success: true,
    stats,
    wisdomCounts: {
      trade: wisdom.trade.length,
      bot: wisdom.bot.length,
      regime: wisdom.regime.length,
    },
    blueprintCount: blueprints.length,
    observationCount: observations.length,
    observationsByType: {
      trade: observations.filter(o => o.type === 'trade').length,
      bot_action: observations.filter(o => o.type === 'bot_action').length,
      regime_change: observations.filter(o => o.type === 'regime_change').length,
      success: observations.filter(o => o.type === 'success').length,
      failure: observations.filter(o => o.type === 'failure').length,
    },
  });
});

/**
 * POST /auto-perfect-bot/admin/update-config
 * Update generator configuration
 */
router.post('/admin/update-config', authMiddleware, adminMiddleware, (req: Request, res: Response) => {
  const updates = req.body;

  autoPerfectBotGenerator.updateConfig(updates);

  res.json({
    success: true,
    message: 'Configuration updated',
  });
});

// ============================================================
// DASHBOARD SUMMARY ROUTE
// ============================================================

/**
 * GET /auto-perfect-bot/dashboard
 * Get a complete dashboard summary
 */
router.get('/dashboard', authMiddleware, (req: Request, res: Response) => {
  const stats = autoPerfectBotGenerator.getStats();
  const wisdom = autoPerfectBotGenerator.getWisdom();
  const blueprints = autoPerfectBotGenerator.getBlueprints();
  const bestBlueprint = autoPerfectBotGenerator.getBestBlueprint();
  const allBots = botBrain.getAllBots();
  const autoGenBots = allBots.filter(b => b.mutations.includes('auto_generated'));

  res.json({
    success: true,
    dashboard: {
      // Status card
      status: {
        online: true,
        health: stats.systemHealth,
        message: 'Watching and learning continuously',
      },

      // Observation stats
      observations: {
        total: stats.totalObservations,
        trades: stats.tradesWatched,
        bots: stats.botsWatched,
        regimes: stats.regimesWatched,
        lastObserved: stats.lastObservation,
      },

      // Wisdom stats
      wisdom: {
        totalPatterns: wisdom.trade.length + wisdom.bot.length + wisdom.regime.length,
        tradePatterns: wisdom.trade.length,
        botPatterns: wisdom.bot.length,
        regimePatterns: wisdom.regime.length,
        highConfidence: wisdom.trade.filter(w => w.confidence > 0.8).length,
      },

      // Blueprints
      blueprints: {
        total: blueprints.length,
        best: bestBlueprint ? {
          name: bestBlueprint.name,
          confidence: bestBlueprint.overallConfidence,
          predictedWinRate: bestBlueprint.predictedWinRate,
        } : null,
      },

      // Auto-generated bots
      autoGeneratedBots: {
        total: stats.botsAutoGenerated,
        active: autoGenBots.filter(b => b.state === 'working' || b.state === 'trading').length,
        topPerformer: autoGenBots.length > 0
          ? autoGenBots.sort((a, b) =>
              (b.performance.successfulTasks / (b.performance.totalTasks || 1)) -
              (a.performance.successfulTasks / (a.performance.totalTasks || 1))
            )[0]?.name
          : null,
      },

      // Quick actions
      actions: {
        forceGenerateBlueprint: {
          method: 'POST',
          url: '/api/auto-perfect-bot/force-generate-blueprint',
          label: '🔮 Generate Blueprint Now',
        },
        forceGenerateBot: {
          method: 'POST',
          url: '/api/auto-perfect-bot/force-generate-bot',
          label: '🤖 Generate Perfect Bot Now',
        },
        viewWisdom: {
          method: 'GET',
          url: '/api/auto-perfect-bot/wisdom',
          label: '🧠 View All Wisdom',
        },
        viewBlueprints: {
          method: 'GET',
          url: '/api/auto-perfect-bot/blueprints',
          label: '📋 View All Blueprints',
        },
      },
    },
  });
});

export default router;
